### PR TITLE
Personal Portfolio: Desktop version

### PR DESCRIPTION
**Pull request by Chimoneg27**
### Personal Portfolio Last Phase: Desktop Version

**In this last phase I did the following**;

- I added the email icon for my desktop navbar
- I made use of flexbox to adjust the Work title and its line
- I changed the flex direction of the "post-stories" section to row, so it can be viewed side by side
- I added two extra cards in the projects section. I made sure they did not affect the mobile version
- I made sure that only one of the cards had a button
- The cards have been edited to match the desktop's version
- The about me section has also undergone some tiny changes, such as minor alignment changes for the language section
- The form still has three input fields as per instruction
- Lastly, needed effects have been added to the buttons

### CODE REVIEW

**Comment by Chimoneg27** [comment]
### Help

I have already installed my linters, but every time I run the commands I get the following error "bash: npx: command not found". Any suggestions?

**Review by Qoosim — CHANGES_REQUESTED** [review]
#  *Status: Required Changes* :recycle:

Hi @Chimoneg27, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 




## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly fix the MIT License on your README file. It is broken at the moment. You can follow this [link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to properly set it up.

license


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by medaminedev66** [comment]
Hello @Chimoneg27  👋,

_This is an additional review as a result of the second opinion request._

I can see that you pushed changes after requesting a second opinion. When you request SO, please do not push any changes so that we can examine your design and compare it with the changes requested by the last reviewer.

However, most changes requested by @Qoosim are correct. Kindly work on the following changes:
- The first card only present the hover of the card. and that means when the user move in the mouse, the card should take the first design. When the user move out the mouse, the card should take the second design (default design). You may use the hover property for this feature.
First design:
image
Second design:
image
A comment was already added to the Figma design explaining this feature:
image

- The mobile version should be responsive until the desktop screen. That requires you to use responsive values in your CSS rules, like percentages (i.e. width: 80%), instead of pixels. Currently your project cards are not centered and there's more margin to the right than to the left on your design:
image

- In mobile version, The languages, skills and Frameworks are not aligned well. Take a look at the screenshot below, And that means left margin and the right margin of the all elements should be the same:
image
- The textarea on your form on the mobile get stringed. Kindly look into it and fix it.

image

- In desktop version, The languages, skills and Frameworks design looks great. You can ignore the requested change.

Keep rocking 🚀!

**Comment by Chimoneg27** [comment]
> Hello @Chimoneg27 👋,
> 
> _This is an additional review as a result of the second opinion request._
> 
> I can see that you pushed changes after requesting a second opinion. When you request SO, please do not push any changes so that we can examine your design and compare it with the changes requested by the last reviewer.
> 
> However, most changes requested by @Qoosim are correct. Kindly work on the following changes:
> 
> * The first card only present the hover of the card. and that means when the user move in the mouse, the card should take the first design. When the user move out the mouse, the card should take the second design (default design). You may use the hover property for this feature.
>   First design:
> 
> image
> 
> Second design:
> image
> 
> A comment was already added to the Figma design explaining this feature:
> image
> 
> * The mobile version should be responsive until the desktop screen. That requires you to use responsive values in your CSS rules, like percentages (i.e. width: 80%), instead of pixels. Currently your project cards are not centered and there's more margin to the right than to the left on your design:
> 
> image
> 
> * In mobile version, The languages, skills and Frameworks are not aligned well. Take a look at the screenshot below, And that means left margin and the right margin of the all elements should be the same:
> 
> image
> 
> - The textarea on your form on the mobile get stringed. Kindly look into it and fix it.
> image
> 
> * In desktop version, The languages, skills and Frameworks design looks great. You can ignore the requested change.
> 
> Keep rocking 🚀!

Screenshot_20230504_210653_com android chrome
How was I supposed to know this. It said copy the design. I copied the design as it appears on the figma file. You should've been more specific. I did not know that it was supposed to be a hover effect. The first reviewer had no issues with it.

**Comment by Chimoneg27** [comment]
Screenshot (3)

**Here is my mobile version. It appears fine. I do not know what's wrong?**

**Comment by Chimoneg27** [comment]
Screenshot (10)

**This is how my desktop and mobile versions of my portfolio look like on my laptop. Please refer to the first review. I do not know what the issue is.**

Screenshot (11)

**Review by Kamba56 — APPROVED** [review]
Hi @Chimoneg27, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
## Highlights
- [x] Great work using flexbox and grid to layout contents!👏👏👏
- [x] Great work adding the hover effects to the project cards!👏👏👏
- [x] !👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
